// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using edificio_digital.Entity.Data;

#nullable disable

namespace edificio_digital.Entity.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260507160312_AjusteJsonbAuditoria")]
    partial class AjusteJsonbAuditoria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("edificio_digital.Entity.Model.Ambiente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AforoMaximo")
                        .HasColumnType("integer")
                        .HasColumnName("aforo_maximo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<Guid>("DependenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("dependencia_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacion");

                    b.Property<Guid>("PisoId")
                        .HasColumnType("uuid")
                        .HasColumnName("piso_id");

                    b.Property<bool>("Publicable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("publicable");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("DependenciaId");

                    b.HasIndex("PisoId", "Codigo")
                        .IsUnique();

                    b.ToTable("ambientes", "estructura");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.BitacoraAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("accion");

                    b.Property<Guid?>("ActorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_usuario_id");

                    b.Property<string>("AgenteUsuario")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("agente_usuario");

                    b.Property<string>("DireccionIp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("direccion_ip");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_hora");

                    b.Property<string>("RegistroId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("registro_id");

                    b.Property<string>("Tabla")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tabla");

                    b.Property<string>("ValoresAnterioresJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("valores_anteriores_json");

                    b.Property<string>("ValoresNuevosJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("valores_nuevos_json");

                    b.HasKey("Id");

                    b.HasIndex("ActorUsuarioId");

                    b.ToTable("bitacora_auditoria", "auditoria");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.BloqueoAmbiente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<Guid>("AmbienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("ambiente_id");

                    b.Property<DateTime>("BloqueadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bloqueado_en");

                    b.Property<Guid>("BloqueadoPorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("bloqueado_por_usuario_id");

                    b.Property<DateTime?>("DesbloqueadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("desbloqueado_en");

                    b.Property<Guid?>("DesbloqueadoPorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("desbloqueado_por_usuario_id");

                    b.Property<string>("MotivoBloqueo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("motivo_bloqueo");

                    b.Property<string>("MotivoDesbloqueo")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("motivo_desbloqueo");

                    b.HasKey("Id");

                    b.HasIndex("AmbienteId");

                    b.HasIndex("BloqueadoPorUsuarioId");

                    b.HasIndex("DesbloqueadoPorUsuarioId");

                    b.ToTable("bloqueos_ambiente", "recursos");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.Dependencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<Guid>("SedeId")
                        .HasColumnType("uuid")
                        .HasColumnName("sede_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("SedeId", "Codigo")
                        .IsUnique();

                    b.ToTable("dependencias", "estructura");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.DisponibilidadAmbiente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AmbienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("ambiente_id");

                    b.Property<bool>("Disponible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("disponible");

                    b.Property<Guid>("FranjaHorariaId")
                        .HasColumnType("uuid")
                        .HasColumnName("franja_horaria_id");

                    b.Property<DateOnly>("VigenciaDesde")
                        .HasColumnType("date")
                        .HasColumnName("vigencia_desde");

                    b.Property<DateOnly?>("VigenciaHasta")
                        .HasColumnType("date")
                        .HasColumnName("vigencia_hasta");

                    b.HasKey("Id");

                    b.HasIndex("AmbienteId");

                    b.HasIndex("FranjaHorariaId");

                    b.ToTable("disponibilidades_ambiente", "seguridad");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.Edificio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<Guid>("SedeId")
                        .HasColumnType("uuid")
                        .HasColumnName("sede_id");

                    b.HasKey("Id");

                    b.HasIndex("SedeId", "Codigo")
                        .IsUnique();

                    b.ToTable("edificios", "estructura");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.Equipo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AmbienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("ambiente_id");

                    b.Property<string>("CodigoPatrimonial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("codigo_patrimonial");

                    b.Property<Guid>("DependenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("dependencia_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("Serie")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("serie");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("AmbienteId");

                    b.HasIndex("CodigoPatrimonial")
                        .IsUnique();

                    b.HasIndex("DependenciaId");

                    b.ToTable("equipos", "recursos");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.FranjaHoraria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer")
                        .HasColumnName("dia_semana");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_fin");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_inicio");

                    b.HasKey("Id");

                    b.HasIndex("DiaSemana", "HoraInicio", "HoraFin")
                        .IsUnique();

                    b.ToTable("franjas_horarias", "seguridad");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.HistorialConfiguracion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("accion");

                    b.Property<string>("ClaveConfiguracion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("clave_configuracion");

                    b.Property<string>("EjecutadoPor")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("ejecutado_por");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_hora");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modulo");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacion");

                    b.Property<string>("ValorAnterior")
                        .HasColumnType("text")
                        .HasColumnName("valor_anterior");

                    b.Property<string>("ValorNuevo")
                        .HasColumnType("text")
                        .HasColumnName("valor_nuevo");

                    b.HasKey("Id");

                    b.ToTable("historial_configuracion", "auditoria");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.HistorialLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgenteUsuario")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("agente_usuario");

                    b.Property<string>("Causa")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("causa");

                    b.Property<string>("DetalleError")
                        .HasColumnType("text")
                        .HasColumnName("detalle_error");

                    b.Property<string>("DireccionIp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("direccion_ip");

                    b.Property<bool>("Exitoso")
                        .HasColumnType("boolean")
                        .HasColumnName("exitoso");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_hora");

                    b.Property<string>("UsuarioIntentado")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("usuario_intentado");

                    b.HasKey("Id");

                    b.ToTable("historial_login", "auditoria");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.HistorialMovimientoGlobal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("accion");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("creado_por");

                    b.Property<string>("DetalleJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("detalle_json");

                    b.Property<string>("EliminadoPor")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("eliminado_por");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entidad");

                    b.Property<string>("EntidadId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entidad_id");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_hora");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("modificado_por");

                    b.Property<string>("Motivo")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("motivo");

                    b.HasKey("Id");

                    b.ToTable("historial_movimiento_global", "auditoria");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.HistorialTipoAmbiente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AmbienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("ambiente_id");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_cambio");

                    b.Property<string>("MotivoCambio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("motivo_cambio");

                    b.Property<string>("TipoAnterior")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_anterior");

                    b.Property<string>("TipoNuevo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_nuevo");

                    b.HasKey("Id");

                    b.HasIndex("AmbienteId");

                    b.ToTable("historial_tipo_ambiente", "recursos");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.HistorialUsoAmbiente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AmbienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("ambiente_id");

                    b.Property<DateTime?>("Fin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fin");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inicio");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacion");

                    b.Property<Guid?>("ReservaId")
                        .HasColumnType("uuid")
                        .HasColumnName("reserva_id");

                    b.Property<string>("TipoUso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_uso");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("AmbienteId");

                    b.HasIndex("ReservaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("historial_uso_ambiente", "reservas");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.HistorialUsoEquipo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AmbienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("ambiente_id");

                    b.Property<Guid>("EquipoId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipo_id");

                    b.Property<DateTime?>("Fin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fin");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inicio");

                    b.Property<string>("Motivo")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("motivo");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("AmbienteId");

                    b.HasIndex("EquipoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("historial_uso_equipo", "recursos");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.Permiso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("accion");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("codigo");

                    b.Property<string>("Recurso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("recurso");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("permisos", "seguridad");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.Piso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<Guid>("EdificioId")
                        .HasColumnType("uuid")
                        .HasColumnName("edificio_id");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.HasKey("Id");

                    b.HasIndex("EdificioId", "Numero")
                        .IsUnique();

                    b.ToTable("pisos", "estructura");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.PrioridadReserva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<int>("AntelacionHoras")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("antelacion_horas");

                    b.Property<int>("NivelPrioridad")
                        .HasColumnType("integer")
                        .HasColumnName("nivel_prioridad");

                    b.Property<Guid?>("RolId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_id");

                    b.Property<string>("TipoUsuario")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_usuario");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("prioridades_reserva", "seguridad");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.Reserva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AmbienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("ambiente_id");

                    b.Property<Guid?>("DependenciaSolicitanteId")
                        .HasColumnType("uuid")
                        .HasColumnName("dependencia_solicitante_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<TimeOnly?>("HoraFin")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_fin");

                    b.Property<TimeOnly?>("HoraInicio")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_inicio");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("motivo");

                    b.Property<int>("PrioridadAplicada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("prioridad_aplicada");

                    b.Property<string>("ReglaRecurrencia")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("regla_recurrencia");

                    b.Property<Guid>("SolicitanteId")
                        .HasColumnType("uuid")
                        .HasColumnName("solicitante_id");

                    b.Property<string>("TipoFranja")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_franja");

                    b.Property<string>("TipoReserva")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_reserva");

                    b.HasKey("Id");

                    b.HasIndex("AmbienteId");

                    b.HasIndex("DependenciaSolicitanteId");

                    b.HasIndex("SolicitanteId");

                    b.ToTable("reservas", "reservas");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.ReservaCalendarioDia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_fin");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_inicio");

                    b.Property<Guid>("ReservaId")
                        .HasColumnType("uuid")
                        .HasColumnName("reserva_id");

                    b.HasKey("Id");

                    b.HasIndex("ReservaId", "Fecha", "HoraInicio", "HoraFin");

                    b.ToTable("reservas_calendario_dia", "reservas");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.RolPermiso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("PermisoId")
                        .HasColumnType("uuid")
                        .HasColumnName("permiso_id");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_id");

                    b.HasKey("Id");

                    b.HasIndex("PermisoId");

                    b.HasIndex("RolId", "PermisoId")
                        .IsUnique();

                    b.ToTable("roles_permisos", "seguridad");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.Sede", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("direccion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("sedes", "estructura");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.Usuario.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("codigo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("roles", "usuario");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.Usuario.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("contrasena");

                    b.Property<Guid?>("DependenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("dependencia_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("correo");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_usuario");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("DependenciaId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("usuarios", "usuario");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.Usuario.UsuarioRol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<DateTime>("VigenciaDesde")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vigencia_desde");

                    b.Property<DateTime?>("VigenciaHasta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vigencia_hasta");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.HasIndex("UsuarioId", "RolId", "VigenciaDesde")
                        .IsUnique();

                    b.ToTable("usuarios_roles", "usuario");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.Ambiente", b =>
                {
                    b.HasOne("edificio_digital.Entity.Model.Dependencia", "Dependencia")
                        .WithMany("Ambientes")
                        .HasForeignKey("DependenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("edificio_digital.Entity.Model.Piso", "Piso")
                        .WithMany("Ambientes")
                        .HasForeignKey("PisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dependencia");

                    b.Navigation("Piso");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.BitacoraAuditoria", b =>
                {
                    b.HasOne("edificio_digital.Entity.Model.Usuario.Usuario", "ActorUsuario")
                        .WithMany()
                        .HasForeignKey("ActorUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActorUsuario");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.BloqueoAmbiente", b =>
                {
                    b.HasOne("edificio_digital.Entity.Model.Ambiente", "Ambiente")
                        .WithMany("Bloqueos")
                        .HasForeignKey("AmbienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("edificio_digital.Entity.Model.Usuario.Usuario", "BloqueadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("BloqueadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("edificio_digital.Entity.Model.Usuario.Usuario", "DesbloqueadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("DesbloqueadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Ambiente");

                    b.Navigation("BloqueadoPorUsuario");

                    b.Navigation("DesbloqueadoPorUsuario");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.Dependencia", b =>
                {
                    b.HasOne("edificio_digital.Entity.Model.Sede", "Sede")
                        .WithMany("Dependencias")
                        .HasForeignKey("SedeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sede");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.DisponibilidadAmbiente", b =>
                {
                    b.HasOne("edificio_digital.Entity.Model.Ambiente", "Ambiente")
                        .WithMany("Disponibilidades")
                        .HasForeignKey("AmbienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("edificio_digital.Entity.Model.FranjaHoraria", "FranjaHoraria")
                        .WithMany("Disponibilidades")
                        .HasForeignKey("FranjaHorariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ambiente");

                    b.Navigation("FranjaHoraria");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.Edificio", b =>
                {
                    b.HasOne("edificio_digital.Entity.Model.Sede", "Sede")
                        .WithMany("Edificios")
                        .HasForeignKey("SedeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sede");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.Equipo", b =>
                {
                    b.HasOne("edificio_digital.Entity.Model.Ambiente", "Ambiente")
                        .WithMany("Equipos")
                        .HasForeignKey("AmbienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("edificio_digital.Entity.Model.Dependencia", "Dependencia")
                        .WithMany("Equipos")
                        .HasForeignKey("DependenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ambiente");

                    b.Navigation("Dependencia");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.HistorialTipoAmbiente", b =>
                {
                    b.HasOne("edificio_digital.Entity.Model.Ambiente", "Ambiente")
                        .WithMany("HistorialTipos")
                        .HasForeignKey("AmbienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ambiente");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.HistorialUsoAmbiente", b =>
                {
                    b.HasOne("edificio_digital.Entity.Model.Ambiente", "Ambiente")
                        .WithMany("HistorialUsoAmbientes")
                        .HasForeignKey("AmbienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("edificio_digital.Entity.Model.Reserva", "Reserva")
                        .WithMany("HistorialUsoAmbientes")
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("edificio_digital.Entity.Model.Usuario.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Ambiente");

                    b.Navigation("Reserva");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.HistorialUsoEquipo", b =>
                {
                    b.HasOne("edificio_digital.Entity.Model.Ambiente", "Ambiente")
                        .WithMany("HistorialUsoEquipos")
                        .HasForeignKey("AmbienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("edificio_digital.Entity.Model.Equipo", "Equipo")
                        .WithMany("HistorialUso")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("edificio_digital.Entity.Model.Usuario.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Ambiente");

                    b.Navigation("Equipo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.Piso", b =>
                {
                    b.HasOne("edificio_digital.Entity.Model.Edificio", "Edificio")
                        .WithMany("Pisos")
                        .HasForeignKey("EdificioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Edificio");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.PrioridadReserva", b =>
                {
                    b.HasOne("edificio_digital.Entity.Model.Usuario.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.Reserva", b =>
                {
                    b.HasOne("edificio_digital.Entity.Model.Ambiente", "Ambiente")
                        .WithMany("Reservas")
                        .HasForeignKey("AmbienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("edificio_digital.Entity.Model.Dependencia", "DependenciaSolicitante")
                        .WithMany()
                        .HasForeignKey("DependenciaSolicitanteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("edificio_digital.Entity.Model.Usuario.Usuario", "Solicitante")
                        .WithMany()
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ambiente");

                    b.Navigation("DependenciaSolicitante");

                    b.Navigation("Solicitante");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.ReservaCalendarioDia", b =>
                {
                    b.HasOne("edificio_digital.Entity.Model.Reserva", "Reserva")
                        .WithMany("CalendarioDias")
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.RolPermiso", b =>
                {
                    b.HasOne("edificio_digital.Entity.Model.Permiso", "Permiso")
                        .WithMany("RolesPermisos")
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("edificio_digital.Entity.Model.Usuario.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.Usuario.Usuario", b =>
                {
                    b.HasOne("edificio_digital.Entity.Model.Dependencia", null)
                        .WithMany("Usuarios")
                        .HasForeignKey("DependenciaId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.Usuario.UsuarioRol", b =>
                {
                    b.HasOne("edificio_digital.Entity.Model.Usuario.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("edificio_digital.Entity.Model.Usuario.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.Ambiente", b =>
                {
                    b.Navigation("Bloqueos");

                    b.Navigation("Disponibilidades");

                    b.Navigation("Equipos");

                    b.Navigation("HistorialTipos");

                    b.Navigation("HistorialUsoAmbientes");

                    b.Navigation("HistorialUsoEquipos");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.Dependencia", b =>
                {
                    b.Navigation("Ambientes");

                    b.Navigation("Equipos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.Edificio", b =>
                {
                    b.Navigation("Pisos");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.Equipo", b =>
                {
                    b.Navigation("HistorialUso");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.FranjaHoraria", b =>
                {
                    b.Navigation("Disponibilidades");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.Permiso", b =>
                {
                    b.Navigation("RolesPermisos");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.Piso", b =>
                {
                    b.Navigation("Ambientes");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.Reserva", b =>
                {
                    b.Navigation("CalendarioDias");

                    b.Navigation("HistorialUsoAmbientes");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.Sede", b =>
                {
                    b.Navigation("Dependencias");

                    b.Navigation("Edificios");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.Usuario.Rol", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("edificio_digital.Entity.Model.Usuario.Usuario", b =>
                {
                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
